
services:
  # DB cho user_service
  user_db:
    image: mysql:8.0
    container_name: user_db
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_service_db
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - ./db/user_service_db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql-config/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - healthcare_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  user_service:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: user_service_runtime
#      ./backend/user_service
    container_name: user_service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://user_db:3306/user_service_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE= http://admin:admin@eureka-server:8761/eureka/

    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      user_db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - healthcare_net

  # DB cho appointment_service
  appointment_db:
    image: mysql:8.0
    container_name: appointment_db
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appointment_service_db
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3308:3306"
    volumes:
      - ./db/appointment_service_db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql-config/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - healthcare_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  appointment_service:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: appointment_service_runtime
    container_name: appointment_service
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:mysql://appointment_db:3306/appointment_service_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://admin:admin@eureka-server:8761/eureka/
    depends_on:
      appointment_db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - healthcare_net

  # gateway_service
  gateway_service:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: gateway_service_runtime
    container_name: gateway_service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://admin:admin@eureka-server:8761/eureka/

    ports:
      - "8080:8080"
    depends_on:
      - appointment_service
      - user_service
      - notification_service
      - eureka-server
    networks:
      - healthcare_net

  #notification_service
  # notification_service_db
  notification_db:
    image: mysql:8.0
    container_name: notification_db
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notification_service_db
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3309:3306"
    volumes:
      - ./db/notification_service_db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql-config/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - healthcare_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  notification_service:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: notification_service_runtime
    container_name: notification_service
    ports:
      - "8084:8084"
    environment:
      SERVER_PORT: 8084
      SPRING_DATASOURCE_URL: jdbc:mysql://notification_db:3306/notification_service_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://admin:admin@eureka-server:8761/eureka/
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

    depends_on:
      notification_db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - healthcare_net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - healthcare_net

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - healthcare_net

  # Eureka Server
  eureka-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: eureka_server_runtime
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_USERNAME=admin
      - EUREKA_PASSWORD=admin
    networks:
      - healthcare_net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  #   frontend
  frontend:
    build: ./frontend/healthcare-app
    container_name: healthcare_frontend
    ports:
      - "5173:5173"
    depends_on:
      - gateway_service
    networks:
      - healthcare_net

networks:
  healthcare_net:
    driver: bridge
